apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-service
  namespace: wanderlust
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: listing-service
  template:
    metadata:
      labels:
        app: listing-service
    spec:
      containers:
        - name: listing-service
          image: ghcr.io/baghel004/wanderlust-listing-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4002
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4002"
            - name: REVIEW_SERVICE_URL
              value: "http://review-service:4003"
            - name: LISTINGS_DB_URL
              valueFrom:
                secretKeyRef:
                  name: wanderlust-secrets
                  key: LISTINGS_DB_URL
            - name: MAP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wanderlust-secrets
                  key: MAP_TOKEN
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: wanderlust-secrets
                  key: CLOUD_NAME
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wanderlust-secrets
                  key: CLOUD_API_KEY
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: wanderlust-secrets
                  key: CLOUD_API_SECRET
          resources:
            requests:
              memory: "80Mi"
              cpu: "50m"
            limits:
              memory: "160Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 25
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: listing-service
  namespace: wanderlust
spec:
  selector:
    app: listing-service
  ports:
    - port: 4002
      targetPort: 4002
